Update zh_CN
BlueMap-Minecraft/BlueMapVue pull request #21
Opened 2021-04-09 01:36 UTC by SettingDust

2021-04-09 08:43 UTC, TBlueF commented
@ahdg6 do you want to review this, before i merge it?

2021-04-09 10:47 UTC, ahdg6 commented
It should be ok to merge after changing some inappropriate translation.

2021-04-09 16:01 UTC, ahdg6 requested changes
Debug要保留，因为调试在发表问题时不是通用的，我的建议是更改为 Debug 调试
Tile 不仅包含了图块，还包含了各类实体数据，MoJang 官方尚未有任何正式翻译，建议保留

2021-04-09 16:01 UTC, ahdg6 commented on public/lang/zh_CN.js
> +        tooltip: "清空图块缓存"
Tile should't be translated as there is no official translation.

2021-04-09 16:01 UTC, ahdg6 commented on public/lang/zh_CN.js
> +        button: "调试"
I strongly suggest that remain 'debug' in translation word.

2021-04-09 16:27 UTC, TBlueF commented
Thanks for the review!
I'll leave this open for discussion, and wait for you guys to tell me when this is ready to be merged :)

2021-04-09 23:16 UTC, SettingDust commented
> Debug要保留，因为调试在发表问题时不是通用的，我的建议是更改为 Debug 调试
> Tile 不仅包含了图块，MoJang 官方尚未有任何正式翻译，建议保留

Debug -> 调试 专有翻译，就是一样的意思，觉得不通用，请举出例子，而不是主观表达

Tile 和 Mojang 无任何关系，非说有也只是本地化键值方块名开头是 tile。根据语境指的是材质及区块（非 MC 区块）信息缓存。
而“不仅包含了图块”
什么是图块？包含了什么？

Tile 指的是“瓷砖”一类，可以通过拼接组成一个整体，这里参考了 Terraria 中的翻译“图格”

2021-04-10 01:48 UTC, ahdg6 approved these changes
> Debug -> 调试 专有翻译，就是一样的意思，觉得不通用，请举出例子，而不是主观表达

我并不打算去争论，我只是见到过很多插件或mod译者都没译 Debug，可能是我见错误例子过多了再加上才疏学浅被带偏了，如果您认为这是社区中较为通用的翻译，我没有异议
> Tile 和 Mojang 无任何关系，非说有也只是本地化键值方块名开头是 tile。根据语境指的是材质及区块（非 MC 区块）信息缓存。
> Tile 指的是“瓷砖”一类，可以通过拼接组成一个整体，这里参考了 Terraria 中的翻译“图格”

就目前来说 “图块” 确实是符合语境的翻译，但从我的角度来看，我更愿意追求严复在翻译时提出的“信”，即忠于原文。因为我们无法预测译词在今后的通用性。您也提到了 Tile 是材质及区块的信息缓存，“图块” 如果在社区中也是较为通用且易理解的翻译的话，那我也没什么意见。

2021-04-10 01:48 UTC, ahdg6 commented on public/lang/zh_CN.js
> +        tooltip: "指南针 / 朝北"
语境之下 '罗盘' 更为合适

2021-04-10 04:23 UTC, SettingDust commented on public/lang/zh_CN.js
> +        tooltip: "清空图块缓存"
Tile 在 MC 中代表的是世界之中的方块，即“拼”成世界的 Tile，此处翻译为“清除方块缓存如何？”

2021-04-10 04:46 UTC, ahdg6 commented
@TBlueF After a pleasant exchange, I think this can be merged.

2021-04-10 04:52 UTC, ahdg6 commented on public/lang/zh_CN.js
> +        tooltip: "清空图块缓存"
都行，对于 Tile 目前是没有什么正式翻译的，只要能让用户理解就行了，未来语义变动的话让译词与时俱进就行了。

2021-04-10 05:04 UTC, SettingDust commented
> After a pleasant exchange, I think this can be merged.

看看我上面的回复？
 WAIT XD

2021-04-10 12:16 UTC, ahdg6 approved these changes

2021-04-13 10:41 UTC, merged